add_newline = false
# A minimal left prompt
format = """$directory$character"""
# move the rest of the prompt to the right
right_format = """$all"""

# symbols from https://www.nerdfonts.com/cheat-sheet
# these require a compatible font like: brew install --cask font-jetbrains-mono-nerd-font 

[bun]
symbol = ' '

[c]
symbol = ' '

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[cpp]
symbol = ' '

[deno]
symbol = ' '

[docker_context]
symbol = ' '

[dotnet]
symbol = '󰪮 '

[elixir]
symbol = ' '

[git_status]
ahead = ' [⇡${count}](blue)'
behind = ' [⇣${count}](blue)'
conflicted = '[${count}](red)'
deleted = '[✘${count}](dimmed red)'
diverged = ' [⇡${ahead_count}⇣${behind_count}](blue)'
modified = '[!${count}](yellow)'
renamed = '[»${count}](purple)'
staged = '[+${count}](green)'
style = 'bold white'
untracked = '[?${count}](dimmed white)'

[golang]
symbol = ' '

[helm]
symbol = ' '

[hostname]
ssh_symbol = ' '

[kubernetes]
detect_files = ['Dockerfile']
symbol = ' '

[lua]
symbol = ' '

[memory_usage]
symbol = ' '

[netns]
symbol = ' '

[nix_shell]
symbol = ' '

[ocaml]
symbol = ' '

[package]
symbol = ' '

[perl]
symbol = ' '

[php]
symbol = ' '

[python]
symbol = ' '

[rlang]
symbol = ' '

[ruby]
symbol = ' '

[rust]
symbol = ' '

[scala]
symbol = ' '

[shell]
bash_indicator = ' '
zsh_indicator = ' '

[solidity]
symbol = ' '

[sudo]
symbol = '󰒃 '

[swift]
symbol = ' '

[terraform]
symbol = ' '

[typst]
symbol = ' '

[vagrant]
symbol = ' '

[zig]
symbol = ' '